Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 44080): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 41411): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 52333): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 34654): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 34730): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 49393): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 56535): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 56139): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 54448): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 47179): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 58264): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 59078): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 57586): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 40024): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 53154): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 46860): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 35126): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 58147): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 52355): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 47001): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 49273): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 56338): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 52447): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 59036): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 53090): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 53091): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 37999): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 52777): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 47211): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 33559): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 36258): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 55364): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 48494): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 42290): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 33722): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 47940): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 33023): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 52915): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 49967): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 35150): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 53199): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 50167): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 46584): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 43657): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 47073): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 57676): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 37946): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 56268): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 59313): 
Notification message from (1, 3, 6, 1, 6, 1, 1):('192.168.111.109', 35968): 
Traceback (most recent call last):
  File "src/trapreciver.py", line 92, in <module>
    transportDispatcher.runDispatcher()
  File "/usr/local/lib/python2.7/dist-packages/pysnmp-4.2.4-py2.7.egg/pysnmp/carrier/asynsock/dispatch.py", line 33, in runDispatcher
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "src/trapreciver.py", line 92, in <module>
    transportDispatcher.runDispatcher()
  File "/usr/local/lib/python2.7/dist-packages/pysnmp-4.2.4-py2.7.egg/pysnmp/carrier/asynsock/dispatch.py", line 33, in runDispatcher
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "src/trapreciver.py", line 92, in <module>
    transportDispatcher.runDispatcher()
  File "/usr/local/lib/python2.7/dist-packages/pysnmp-4.2.4-py2.7.egg/pysnmp/carrier/asynsock/dispatch.py", line 33, in runDispatcher
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "src/trapreciver.py", line 92, in <module>
    transportDispatcher.runDispatcher()
  File "/usr/local/lib/python2.7/dist-packages/pysnmp-4.2.4-py2.7.egg/pysnmp/carrier/asynsock/dispatch.py", line 33, in runDispatcher
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "src/trapreciver.py", line 92, in <module>
    transportDispatcher.runDispatcher()
  File "/usr/local/lib/python2.7/dist-packages/pysnmp-4.2.4-py2.7.egg/pysnmp/carrier/asynsock/dispatch.py", line 33, in runDispatcher
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "src/trapreciver.py", line 85, in <module>
    udp.domainName, udp.UdpSocketTransport().openServerMode((cm.getTrapIp(), 5050))
  File "/usr/local/lib/python2.7/dist-packages/pysnmp-4.2.4-py2.7.egg/pysnmp/carrier/asynsock/dgram/base.py", line 41, in openServerMode
pysnmp.carrier.error.CarrierError: bind() for ('192.168.111.126', 5050) failed: [Errno 98] Address already in use
Traceback (most recent call last):
  File "src/trapreciver.py", line 85, in <module>
    udp.domainName, udp.UdpSocketTransport().openServerMode((cm.getTrapIp(), 5050))
  File "/usr/local/lib/python2.7/dist-packages/pysnmp-4.2.4-py2.7.egg/pysnmp/carrier/asynsock/dgram/base.py", line 41, in openServerMode
pysnmp.carrier.error.CarrierError: bind() for ('192.168.111.126', 5050) failed: [Errno 98] Address already in use
